main/urls.py
from django.urls import path

from .views import index
from .views import doska_page
from .views import brus_page
from .views import brusok_page
from .views import vagonka_page
from .views import imitacia_page
from .views import terasnaya_page
from .views import shpuntovanaya_page
from .views import barlinek_page
from .views import askania_page
from .views import almond_page
from .views import askania_grande
from .views import calvados_grande
from .views import caramel_grande
from .views import ivory_grande
from .views import porto_grande
from .views import white_truffle_grande
from .views import yasen_coffe_grande
from .views import hazelnut_grande
from .views import lemon_sorbet_grande
from .views import barlinek2
from .views import almond_piccolo
from .views import apricot_sorbet_piccolo
from .views import brown_shugar_piccolo
from .views import coconut_piccolo
from .views import espresso_piccolo
from .views import nugat_piccolo
from .views import peach_piccolo
from .views import snowflakes_piccolo
from .views import caldera_piccolo




app_name = 'main'
urlpatterns = [
    path('', index, name='index'),
    path('<str:page>/', doska_page, name='doska'),
    path('<str:page>/', brus_page, name='brus'),
    path('<str:page>/', brusok_page, name='brusok'),
    path('<str:page>/', vagonka_page, name='vagonka'),
    path('<str:page>/', imitacia_page, name='imitacia_brusa'),
    path('<str:page>/', terasnaya_page, name='terasnaya_doska'),
    path('<str:page>/', shpuntovanaya_page, name='shpuntovanaya_doska'),
    path('<str:page>/', barlinek_page, name='barlinek'),
    path('<str:page>/', askania_page, name='Askania-piccolo'),
    path('<str:page>/', almond_page, name='Almond_grande'),
    path('<str:page>/', askania_grande, name='Askania_grande'),
    path('<str:page>/', calvados_grande, name='Calvados_grande'),
    path('<str:page>/', caramel_grande, name='Caramel_grande'),
    path('<str:page>/', ivory_grande, name='Ivory_grande'),
    path('<str:page>/', porto_grande, name='Porto_grande'),
    path('<str:page>/', white_truffle_grande, name='White_truffle_grande'),
    path('<str:page>/', yasen_coffe_grande, name='Yasen_coffe_grande'),
    path('<str:page>/', hazelnut_grande, name='Hazelnut_grande'),
    path('<str:page>/', lemon_sorbet_grande, name='Lemon_sorbet_grande'),
    path('<str:page>/', barlinek2, name='Barlinek_piccolo'),
    path('<str:page>/', almond_piccolo, name='Almond_piccolo'),
    path('<str:page>/', apricot_sorbet_piccolo, name='Apricot_sorbet_piccolo'),
    path('<str:page>/', brown_shugar_piccolo, name='Brown_shugar_piccolo'),
    path('<str:page>/', coconut_piccolo, name='Coconut_piccolo'),
    path('<str:page>/', espresso_piccolo, name='Espresso_piccolo'),
    path('<str:page>/', nugat_piccolo, name='Nugat_piccolo'),
    path('<str:page>/', peach_piccolo, name='Peach_piccolo'),
    path('<str:page>/', snowflakes_piccolo, name='Snowflakes_piccolo'),
    path('<str:page>/', caldera_piccolo, name='Caldera_piccolo'),


]

wdmrt/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.views import serve
from django.views.decorators.cache import never_cache


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='')),
]
if settings.DEBUG:
    urlpatterns.append(path('static/<path:path>', never_cache(serve)))

main/models.py
# coding=utf-8
from django.db import models






# Create your models here.

main/views.py
# coding=utf-8
from django.shortcuts import render
from django.template import TemplateDoesNotExist
from django.http import HttpResponse, Http404
from django.template.loader import get_template
from django.contrib.auth.views import LoginView
from django.contrib.auth.views import LogoutView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.views.generic.edit import UpdateView, CreateView
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.shortcuts import get_object_or_404
from django.contrib.auth.views import PasswordChangeView
from django.views.generic.base import TemplateView
from django.core.signing import BadSignature
from django.views.generic.edit import DeleteView
from django.contrib.auth import logout
from django.contrib import messages
from django.core.paginator import Paginator
from django.db.models import Q
from django.shortcuts import redirect


def index(request):
    return render(request, 'main/index.html')


def doska_page(request, page):
    try:
        template = get_template('main/' + page + '.html')
    except TemplateDoesNotExist:
        raise Http404
    return HttpResponse(template.render(request=request))


def brus_page(request, page):
    try:
        template = get_template('main/' + page + '.html')
    except TemplateDoesNotExist:
        raise Http404
    return HttpResponse(template.render(request=request))


def brusok_page(request, page):
    try:
        template = get_template('main/' + page + '.html')
    except TemplateDoesNotExist:
        raise Http404
    return HttpResponse(template.render(request=request))


def vagonka_page(request, page):
    try:
        template = get_template('main/' + page + '.html')
    except TemplateDoesNotExist:
        raise Http404
    return HttpResponse(template.render(request=request))


def imitacia_page(request, page):
    try:
        template = get_template('main/' + page + '.html')
    except TemplateDoesNotExist:
        raise Http404
    return HttpResponse(template.render(request=request))


def terasnaya_page(request, page):
    try:
        template = get_template('main/' + page + '.html')
    except TemplateDoesNotExist:
        raise Http404
    return HttpResponse(template.render(request=request))


def shpuntovanaya_page(request, page):
    try:
        template = get_template('main/' + page + '.html')
    except TemplateDoesNotExist:
        raise Http404
    return HttpResponse(template.render(request=request))


def other_page(request, page):
    try:
        template = get_template('main/' + page + '.html')
    except TemplateDoesNotExist:
        raise Http404
    return HttpResponse(template.render(request=request))


def barlinek_page(request, page):
    try:
        template = get_template('main/' + page + '.html')
    except TemplateDoesNotExist:
        raise Http404
    return HttpResponse(template.render(request=request))


def askania_page(request, page):
    try:
        template = get_template('main/' + page + '.html')
    except TemplateDoesNotExist:
        raise Http404
    return HttpResponse(template.render(request=request))


def almond_page(request, page):
    try:
        template = get_template('main/' + page + '.html')
    except TemplateDoesNotExist:
        raise Http404
    return HttpResponse(template.render(request=request))


def askania_grande(request, page):
    try:
        template = get_template('main/' + page + '.html')
    except TemplateDoesNotExist:
        raise Http404
    return HttpResponse(template.render(request=request))


def calvados_grande(request, page):
    try:
        template = get_template('main/' + page + '.html')
    except TemplateDoesNotExist:
        raise Http404
    return HttpResponse(template.render(request=request))


def caramel_grande(request, page):
    try:
        template = get_template('main/' + page + '.html')
    except TemplateDoesNotExist:
        raise Http404
    return HttpResponse(template.render(request=request))


def ivory_grande(request, page):
    try:
        template = get_template('main/' + page + '.html')
    except TemplateDoesNotExist:
        raise Http404
    return HttpResponse(template.render(request=request))


def porto_grande(request, page):
    try:
        template = get_template('main/' + page + '.html')
    except TemplateDoesNotExist:
        raise Http404
    return HttpResponse(template.render(request=request))


def white_truffle_grande(request, page):
    try:
        template = get_template('main/' + page + '.html')
    except TemplateDoesNotExist:
        raise Http404
    return HttpResponse(template.render(request=request))


def yasen_coffe_grande(request, page):
    try:
        template = get_template('main/' + page + '.html')
    except TemplateDoesNotExist:
        raise Http404
    return HttpResponse(template.render(request=request))


def hazelnut_grande(request, page):
    try:
        template = get_template('main/' + page + '.html')
    except TemplateDoesNotExist:
        raise Http404
    return HttpResponse(template.render(request=request))


def lemon_sorbet_grande(request, page):
    try:
        template = get_template('main/' + page + '.html')
    except TemplateDoesNotExist:
        raise Http404
    return HttpResponse(template.render(request=request))


def barlinek2(request, page):
    try:
        template = get_template('main/' + page + '.html')
    except TemplateDoesNotExist:
        raise Http404
    return HttpResponse(template.render(request=request))


def almond_piccolo(request, page):
    try:
        template = get_template('main/' + page + '.html')
    except TemplateDoesNotExist:
        raise Http404
    return HttpResponse(template.render(request=request))


def apricot_sorbet_piccolo(request, page):
    try:
        template = get_template('main/' + page + '.html')
    except TemplateDoesNotExist:
        raise Http404
    return HttpResponse(template.render(request=request))


def brown_shugar_piccolo(request, page):
    try:
        template = get_template('main/' + page + '.html')
    except TemplateDoesNotExist:
        raise Http404
    return HttpResponse(template.render(request=request))


def coconut_piccolo(request, page):
    try:
        template = get_template('main/' + page + '.html')
    except TemplateDoesNotExist:
        raise Http404
    return HttpResponse(template.render(request=request))


def espresso_piccolo(request, page):
    try:
        template = get_template('main/' + page + '.html')
    except TemplateDoesNotExist:
        raise Http404
    return HttpResponse(template.render(request=request))


def nugat_piccolo(request, page):
    try:
        template = get_template('main/' + page + '.html')
    except TemplateDoesNotExist:
        raise Http404
    return HttpResponse(template.render(request=request))


def peach_piccolo(request, page):
    try:
        template = get_template('main/' + page + '.html')
    except TemplateDoesNotExist:
        raise Http404
    return HttpResponse(template.render(request=request))


def snowflakes_piccolo(request, page):
    try:
        template = get_template('main/' + page + '.html')
    except TemplateDoesNotExist:
        raise Http404
    return HttpResponse(template.render(request=request))


def snowflakes_piccolo(request, page):
    try:
        template = get_template('main/' + page + '.html')
    except TemplateDoesNotExist:
        raise Http404
    return HttpResponse(template.render(request=request))


def caldera_piccolo(request, page):
    try:
        template = get_template('main/' + page + '.html')
    except TemplateDoesNotExist:
        raise Http404
    return HttpResponse(template.render(request=request))


class BBLoginView(LoginView):
    template_name = 'main/login.html'


class BBLogoutView(LoginRequiredMixin, LogoutView):
    template_name = 'main/logout.html'


@login_required
def profile(request):
    bbs = Bb.objects.filter(author=request.user.pk)
    context = {'bbs': bbs}
    return render(request, 'main/profile.html', context)

# Create your views here.

templates/main/Almond_grande.html
{% extends "layout/basic.html" %}
{% load bootstrap4 %}



{% block content %}
<div class="container">
   <div class="row"style="margin-top:20px">
        <div class="col-md-3" style="background: #FFFFE0">
<!--<a href="/static/main9/-Askania-Piccolo.jpg" onclick="window.open(this.href, '', 'scrollbars=1,height='+Math.min(640, screen.availHeight)+',width='+Math.min(700, screen.availWidth)); return false;"> <img class="main-image" src="/static/main9/-Askania-Piccolo.jpg"></a>-->
           <img style="margin-top:10px" src = '/static/main9/Almond-Grande-wzronik.jpg' alt = 'Фотография' width = '340' onclick = 'openImageWindow(this.src);' />
        </div>
       <div class="col-md-6 "  style="background:#FFFFE0	;">
        <h4 class="text-center" style="margin-top:50px">ПАРКЕТНАЯ ДОСКА
            ДУБ ALMOND GRANDEO</h4>

        <b>Страна: Польша, Украина </b><br>
        <b>Поизводитель: "Barlinek", www.barlinek.com<br></b>
        <br>Тип доски: Однополосный<br>
            Толщина доски: 14мм<br>
        Материал: дуб<br>
        Гарантия: 20 лет<br>
        Тип замка: 5gc<br>
        Площадь упаковки: 2,77м^2 <br>
        Штук в упаковке: 7шт <br>
        Размер: 14х180х2200 мм<br>
        Фаска: с фаской, фаска четырехсторонняя <br>
        Поверхность: матовый, браширование, лак<br>
        Артикул: 5645654<br><br><br>

       </div>
     <div class="col-md-3 text-center" style=" background:white;">
         <h6  style="margin-top:20px">Цена за метр:</h6><h5>3650 руб.</h5>
         <h6 >Цена за упаковку:</h6><h5> 10100 руб.</h5><br>
         <h5>Упаковка: 2,77м^2</h5>
         <h5 class="text-center"><a style="color:red"  href="tel:+79817375216">
             Позвоните нам для того чтобы оформить заказ:<br> 8-981-737-52-16</a></h5>

     </div>
       <div class="jumbotron font-italic " style="margin-top:20px; background:white">
          <h3 class="text-center font-italic">Описание паркетной доски Дуб Almond Grande</h3>
          <p >Современные технологии, экологичные материалы, современный
              дизайн и непревзойдённое качество от Barlinek воплотились в паркетной доске
              Дуб Almond Grande из коллекции PURE Line. Дуб Almond Grande соответствует
              международным стандартам качества ISO-9001 и международным экологическим
              стандартам по сертификатам ISO 14001. Все продукты Barlinek проходят высокоточную
              обработку и имеют качественный замок, что делает процесс укладки простым и быстрым!</p><br>
          <h3 class="text-center">Дуб Askania Grande на прямую со склада </h3>
          <b>Вы всегда сможете посмотреть образцы и проконсультироваться у наших специалистов у нас на складе, который находится
              по адресу: Выборгская наб.55</b>
           <h3 class="text-center"><br>Оплата и доставка</h3>
          <p>
              Наша комапния готова предложить вам оптовую поставку паркетной доски Дуб Almond Grande любого объёма в
              кратчайшие сроки! Мы осуществляем доставку по Санкт-Петербургу и Ленинградской области, а также и в другие регионы Северо-Запада.</p>
          <hr class="my-2">
          <p class="lead">
             <h5 class="text-center"><a style="color:red"  href="tel:+79817375216">
             Позвоните нам для того чтобы оформить заказ или проконсультироваться у наших специалистов:<br> 8-981-737-52-16</a></h5>
           </p>
        </div>
   </div>
</div>


{% endblock %}

templates/main/Almond_piccolo.html
{% extends "layout/basic.html" %}
{% load bootstrap4 %}



{% block content %}
<div class="container">
   <div class="row"style="margin-top:20px">
        <div class="col-md-3" style="background: #FFFFE0">
           <img style="margin-top:10px" src = '/static/main9/Almond-Piccolo.jpg' alt = 'Фотография' width = '340' onclick = 'openImageWindow(this.src);' />
        </div>
       <div class="col-md-6 "  style="background:#FFFFE0	;">
            <h4 class="text-center" style="margin-top:50px">ПАРКЕТНАЯ ДОСКА
               ДУБ ALMOND PICCOLO</h4>
           <p>
               Дубовый пол нежного, белого окраса. Доски имеют структуру подчеркнутую
               брашированием, a четырехсторонняя микрофаска придает доскам легкости,
               защищенную матовым лаком.
           </p>
            <b>Страна: Польша, Украина </b><br>
            <b>Поизводитель: "Barlinek", www.barlinek.com<br></b>
            <br>Тип доски: Однополосный<br>
            Толщина доски: 14мм<br>
            Материал: дуб<br>
            Гарантия: 20 лет<br>
            Тип замка: 5gc<br>
            Площадь упаковки: 0,99м^2 <br>
            Штук в упаковке: 7 шт. <br>
            Размер: 14х130х1092мм<br>
            Фаска: без фаски <br>
            Поверхность: матовый, масло<br>
            Артикул: 21435<br><br><br>

       </div>
         <div class="col-md-3 text-center" style=" background:white;">
             <h6  style="margin-top:20px">Цена за метр:</h6><h5>2600 руб.</h5>
             <h6 >Цена за упаковку:</h6><h5> 2574 руб.</h5><br>
             <h5>Упаковка: 2,77м^2</h5>
             <h5 class="text-center"><a style="color:red"  href="tel:+79817375216">
                 Позвоните нам для того чтобы оформить заказ:<br> 8-981-737-52-16</a></h5>

         </div>
       <div class="jumbotron font-italic " style="margin-top:20px; background:white">
          <h3 class="text-center font-italic">Описание паркетной доски Дуб Almond Piccolo</h3>
          <p >Современные технологии, экологичные материалы, современный дизайн и непревзойдённое
              качество от Barlinek воплотились в паркетной доске Дуб Almond Piccolo из коллекции
              PURE Line. Дуб Almond Piccolo соответствует международным стандартам качества ISO-9001
              и международным экологическим стандартам по сертификатам ISO 14001. Все продукты Barlinek
              проходят высокоточную обработку и имеют качественный замок, что делает процесс укладки простым и быстрым!
          </p><br>
           <h3 class="text-center"> Дуб Almond Piccolo на прямую со склада </h3>
          <b>Вы всегда сможете посмотреть образцы и проконсультироваться у наших специалистов у нас на складе, который находится
              по адресу: Выборгская наб.55 </b>

          <h3 class="text-center"><br>Оплата и доставка</h3>
          <p>
              Наша комапния готова предложить вам оптовую поставку паркетной доски любого объёма в
              кратчайшие сроки! Мы осуществляем доставку по Санкт-Петербургу и Ленинградской области, а также и в
              другие регионы Северо-Запада.</p>
          <hr class="my-2">
          <p class="lead"><br>
             <h5 class="text-center"><a style="color:red"  href="tel:+79817375216">
             Позвоните нам для того чтобы оформить заказ или проконсультироваться у наших специалистов:<br> 8-981-737-52-16</a></h5>
           </p>
        </div>
   </div>
</div>


{% endblock %}

templates/main/barlinek.html
{% extends "layout/basic.html" %}

{% block content %}


<div class="container">
    <div class="row" style="margin-top: 10px">
        <div style="background:white" class="text-black-50 text-center"><h5> <br>Группа компаний Barlinek -
            это один из мировых лидеров по производству
            деревянных напольных покрытий с суммарной мощностью
            производства более 9 миллионов квадратных метров в год.
            Главный продукт компании – паркетная доска Barlinek,
            которая производится из благородных видов древесины.</h5>
            <br>

  <ul class="pagination pagination-sm" style="margin-left:20px">
    <li >
      <h4> Серии Barlinek:</h4>
    </li>
    <li class="page-item"><a class="btn btn-warning" href="{% url 'main:barlinek' page='barlinek' %}">Grande</a></li>
    <li class="page-item"><a class="btn btn-info"href="{% url 'main:Barlinek_piccolo' page='Barlinek_piccolo' %}">Piccolo</a></li>
    <li class="page-item"><a  class="btn btn-success" href="#">Molti</a></li>
    <li class="page-item">
    </li>
  </ul>
        <h4 style="color:black">Серия Barlinek Grande:</h4>
        </div>
        <div class="col-sm2" >
          <div class="card-sm text-center" >
              <ul class="list-unstyled"  >
                 <a href="{% url 'main:Almond_grande' page='Almond_grande' %}">
                    <div class="card-body"style="color:black">
                      <div class="card">
                      <img class="card-img-top main-image" src="/static/main9/Almond-Grande-wzronik.jpg"  >
                      <div class="card-body">
                        <h5 class="card-title">Паркетная доска <br>дуб<br>ALMOND GRANDE</h5>
                        <p class="card-text">
                            Тип: Однополосный</p>
                          <b>Габариты:14х180х2200</b><br>
                        <b>Цена за м^2: 3650 руб.
                            <br>Упаковка: 11000 руб.</b>
                        </p>
                      </div>
                     </div>
                    </div>
                 </a>
              </ul>
          </div>
        </div>
        <div class="col-sm2" >
          <div class="card-sm text-center" >
              <ul class="list-unstyled"  >
                 <a href="{% url 'main:Askania_grande' page='Askania_grande' %}">
                    <div class="card-body"style="color:black">
                      <div class="card">
                      <img class="card-img-top main-image" src="/static/main9/-Askania-Grande.jpg"  >
                      <div class="card-body">
                        <h5 class="card-title">Паркетная доска <br>
                            дуб <br>ASKANIA GRANDE</h5>
                        <p class="card-text">
                            Тип: Однополосный</p>
                          <b>Габариты:14х180х2200</b><br>
                        <b>Цена за м^2: 3700 руб.
                            <br> Упаковка: 10250 руб.
                        </b>
                      </div>
                     </div>
                    </div>
                 </a>
              </ul>
          </div>
        </div>
        <div class="col-sm2" >
          <div class="card-sm text-center" >
              <ul class="list-unstyled"  >
                 <a href="{% url 'main:Calvados_grande' page='Calvados_grande' %}">
                    <div class="card-body"style="color:black">
                      <div class="card">
                      <img class="card-img-top main-image" src="/static/main9/-Calvados-Grande.jpg"  >
                      <div class="card-body">
                        <h5 class="card-title">Паркетная доска <br>
                            дуб <br>CALVADOS GRANDE</h5>
                        <p class="card-text">
                            Тип: Однополосный</p>
                          <b>Габариты:14х180х2200</b><br>
                        <b>Цена за м^2: 4100 руб.
                            <br> Упаковка: 11355 руб.
                        </b>
                      </div>
                     </div>
                    </div>
                 </a>
              </ul>
          </div>
        </div>
        <div class="col-sm2" >
          <div class="card-sm text-center" >
              <ul class="list-unstyled"  >
                 <a href="{% url 'main:Caramel_grande' page='Caramel_grande' %}">
                    <div class="card-body"style="color:black">
                      <div class="card">
                      <img class="card-img-top main-image" src="/static/main9/-Caramel-Grande.jpg"  >
                      <div class="card-body">
                        <h5 class="card-title">Паркетная доска <br>
                            дуб <br>CARAMEL GRANDE</h5>
                        <p class="card-text">
                            Тип: Однополосный</p>
                          <b>Габариты:14х180х2200</b><br>
                        <b>Цена за м^2: 4050 руб.
                            <br> Упаковка: 11218 руб.
                        </b>
                      </div>
                     </div>
                    </div>
                 </a>
              </ul>
          </div>
        </div>
        <div class="col-sm2" >
          <div class="card-sm text-center" >
              <ul class="list-unstyled"  >
                 <a href="{% url 'main:Ivory_grande' page='Ivory_grande' %}">
                    <div class="card-body"style="color:black">
                      <div class="card">
                      <img class="card-img-top main-image" src="/static/main9/-Ivory-Grande.jpg"  >
                      <div class="card-body">
                        <h5 class="card-title">Паркетная доска <br>
                            дуб <br>IVORY GRANDE</h5>
                        <p class="card-text"><br>
                            Тип: Однополосный</p>
                          <b>Габариты:14х180х2200</b><br>
                        <b>Цена за м^2: 3800 руб.
                            <br> Упаковка: 10526 руб.<br>
                        </b>
                        </b>
                      </div>
                     </div>
                    </div>
                 </a>
              </ul>
          </div>
        </div>
        <div class="col-sm2" >
          <div class="card-sm text-center" >
              <ul class="list-unstyled"  >
                 <a href="{% url 'main:Porto_grande' page='Porto_grande' %}">
                    <div class="card-body"style="color:black">
                      <div class="card">
                      <img class="card-img-top main-image" src="/static/main9/-Porto-Grande.jpg"  >
                      <div class="card-body">
                        <h5 class="card-title">Паркетная доска <br>
                            дуб <br>PORTO GRANDE</h5>
                        <p class="card-text"><br>
                            Тип: Однополосный</p>
                          <b>Габариты:180х2200</b><br>
                        <b>Цена за м^2: 3800 руб.
                            <br>Упаковка: 10526 руб.
                        </b>
                      </div>
                     </div>
                    </div>
                 </a>
              </ul>
          </div>
        </div>
        <div class="col-sm2" >
          <div class="card-sm text-center" >
              <ul class="list-unstyled"  >
                 <a href="{% url 'main:White_truffle_grande' page='White_truffle_grande' %}">
                    <div class="card-body"style="color:black">
                      <div class="card">
                      <img class="card-img-top main-image" src="/static/main9/-White-Truffle-Grande.jpg"  >
                      <div class="card-body">
                        <h5 class="card-title">Паркетная доска <br>
                            дуб <br>WHITE TRUFFLE<br> GRANDE</h5>
                        <p class="card-text">
                            Тип: Однополосный</p>
                          <b>Габариты:180х2200</b><br>
                        <b>Цена за м^2: 4070 руб.
                            <br> Упаковка: 11273 руб.
                        </b>
                      </div>
                     </div>
                    </div>
                 </a>
              </ul>
          </div>
        </div>
        <div class="col-sm2" >
          <div class="card-sm text-center" >
              <ul class="list-unstyled"  >
                 <a href="{% url 'main:Lemon_sorbet_grande' page='Lemon_sorbet_grande' %}">
                    <div class="card-body"style="color:black">
                      <div class="card">
                      <img class="card-img-top main-image" src="/static/main9/Lemon-Sorbet-Grande.jpg"  >
                      <div class="card-body">
                        <h5 class="card-title">Паркетная доска <br>
                            Ясень <br>LEMON SORBET<br>GRANDE</h5>
                        <p class="card-text">
                            Тип: Однополосный</p>
                          <b>Габариты:180х2200</b><br>
                        <b>Цена за м^2: 3600руб.
                            <br>Упаковка: 9972 руб.
                        </b>
                      </div>
                     </div>
                    </div>
                 </a>
              </ul>
          </div>
        </div>
        <div class="col-sm2" >
          <div class="card-sm text-center" >
              <ul class="list-unstyled"  >
                 <a href="{% url 'main:Yasen_coffe_grande' page='Yasen_coffe_grande' %}">
                    <div class="card-body"style="color:black">
                      <div class="card">
                      <img class="card-img-top main-image" src="/static/main9/-Coffee-Grande.jpg"  >
                      <div class="card-body">
                        <h5 class="card-title">Паркетная доска <br>
                            Ясень <br>COFFEE GRANDE</h5>
                        <p class="card-text">
                            Тип: Однополосный</p>
                          <b>Габариты:180х2200</b><br>
                        <b>Цена за м^2: 3400 руб.
                            <br>Упаковка: 9418 руб.
                        </b>
                      </div>
                     </div>
                    </div>
                 </a>
              </ul>
          </div>
        </div>
        <div class="col-sm2" >
          <div class="card-sm text-center" >
              <ul class="list-unstyled"  >
                 <a href="{% url 'main:Hazelnut_grande' page='Hazelnut_grande' %}">
                    <div class="card-body"style="color:black">
                      <div class="card">
                      <img class="card-img-top main-image" src="/static/main9/-Hazelnut-Grande.jpg"  >
                      <div class="card-body">
                        <h5 class="card-title">Паркетная доска <br>
                            Ясень <br>HAZELNUT GRANDE</h5>
                        <p class="card-text">
                            Тип: Однополосный</p>
                          <b>Габариты:180х2200</b><br>
                        <b>Цена за м^2: 3750руб.
                            <br>Упаковка: 10387 руб.
                        </b>
                      </div>
                     </div>
                    </div>
                 </a>
              </ul>
          </div>
        </div>
    </div>
</div><
  <ul class="pagination pagination-sm" style="margin-left:50px">
    <li >
      <h5 style="color:black; background:white;"> Серии Barlinek:</h5>
    </li>
    <li class="page-item"><a class="btn btn-warning" href="{% url 'main:barlinek' page='barlinek' %}">Grande</a></li>
    <li class="page-item"><a class="btn btn-info"href="{% url 'main:Barlinek_piccolo' page='Barlinek_piccolo' %}">Piccolo</a></li>
    <li class="page-item"><a  class="btn btn-success" href="#">Molti</a></li>
    <li class="page-item">
    </li>
  </ul>
{% endblock %}