main/urls.py
from django.urls import path

from .views import index
from .views import doska_page
from .views import brus_page
from .views import brusok_page
from .views import vagonka_page
from .views import imitacia_page
from .views import terasnaya_page
from .views import shpuntovanaya_page
from .views import barlinek_page
from .views import askania_page
from .views import almond_page
from .views import askania_grande
from .views import calvados_grande
from .views import caramel_grande
from .views import ivory_grande
from .views import porto_grande
from .views import white_truffle_grande
from .views import yasen_coffe_grande
from .views import hazelnut_grande
from .views import lemon_sorbet_grande
from .views import barlinek2
from .views import almond_piccolo
from .views import apricot_sorbet_piccolo
from .views import brown_shugar_piccolo
from .views import coconut_piccolo
from .views import espresso_piccolo
from .views import nugat_piccolo
from .views import peach_piccolo
from .views import snowflakes_piccolo
from .views import caldera_piccolo




app_name = 'main'
urlpatterns = [
    path('', index, name='index'),
    path('<str:page>/', doska_page, name='doska'),
    path('<str:page>/', brus_page, name='brus'),
    path('<str:page>/', brusok_page, name='brusok'),
    path('<str:page>/', vagonka_page, name='vagonka'),
    path('<str:page>/', imitacia_page, name='imitacia_brusa'),
    path('<str:page>/', terasnaya_page, name='terasnaya_doska'),
    path('<str:page>/', shpuntovanaya_page, name='shpuntovanaya_doska'),
    path('<str:page>/', barlinek_page, name='barlinek'),
    path('<str:page>/', askania_page, name='Askania-piccolo'),
    path('<str:page>/', almond_page, name='Almond_grande'),
    path('<str:page>/', askania_grande, name='Askania_grande'),
    path('<str:page>/', calvados_grande, name='Calvados_grande'),
    path('<str:page>/', caramel_grande, name='Caramel_grande'),
    path('<str:page>/', ivory_grande, name='Ivory_grande'),
    path('<str:page>/', porto_grande, name='Porto_grande'),
    path('<str:page>/', white_truffle_grande, name='White_truffle_grande'),
    path('<str:page>/', yasen_coffe_grande, name='Yasen_coffe_grande'),
    path('<str:page>/', hazelnut_grande, name='Hazelnut_grande'),
    path('<str:page>/', lemon_sorbet_grande, name='Lemon_sorbet_grande'),
    path('<str:page>/', barlinek2, name='Barlinek_piccolo'),
    path('<str:page>/', almond_piccolo, name='Almond_piccolo'),
    path('<str:page>/', apricot_sorbet_piccolo, name='Apricot_sorbet_piccolo'),
    path('<str:page>/', brown_shugar_piccolo, name='Brown_shugar_piccolo'),
    path('<str:page>/', coconut_piccolo, name='Coconut_piccolo'),
    path('<str:page>/', espresso_piccolo, name='Espresso_piccolo'),
    path('<str:page>/', nugat_piccolo, name='Nugat_piccolo'),
    path('<str:page>/', peach_piccolo, name='Peach_piccolo'),
    path('<str:page>/', snowflakes_piccolo, name='Snowflakes_piccolo'),
    path('<str:page>/', caldera_piccolo, name='Caldera_piccolo'),


]

wdmrt/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.views import serve
from django.views.decorators.cache import never_cache


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='')),
]
if settings.DEBUG:
    urlpatterns.append(path('static/<path:path>', never_cache(serve)))

templates/layout/basic.html
{% load bootstrap4 %}
{% load thumbnail %}
{% load bootstrap4 %}
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type"
        content="text/html"; charset="utf-8">
        <meta name="viewport"
        content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title>{% block title %}Woodmart{% endblock %} Магазин строительных материлов.</title>
        {% bootstrap_css %}
       <link rel="stylesheet" type="text/css"
        href="{% static 'main9/style.css' %}">
        {% bootstrap_javascript jquery='slim' %}
        {% block searchform %}
        {% endblock %}
        <script type="text/javascript">
          function openImageWindow(src) {
            var image = new Image();
            image.src = src;
            var width = image.width;
            var height = image.height;
            window.open(src,"Image","width=" + width + ",height=" + height);
          }
        </script>
    </head>

<header class="mb-3">
    <h3 class="text-center" style="color:white" >Woodmart магазин строительных материалов.</h3>
</header>
<nav class="navbar navbar-expand-lg navbar-light " style="background:#F0FFF0">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <a class="navbar-brand" href="{% url 'main:index' %}">Главная</a>

  <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
    <ul class="navbar-nav mr-auto mt-2 mt-md-0">
        <li class="nav-item active"></li>
    <div class="dropdown open">
      <button class="btn  dropdown-toggle" style="background:#FAFAD2;" type="button" id="dropdownMenu4" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Пиломатериалы
      </button>
      <div class="dropdown-menu text-center" style="background:#FAFAD2"  >
        <a class="dropdown-item" href="{% url 'main:doska' page='doska' %}">Доска</a>
        <a class="dropdown-item" href="{% url 'main:brus' page='brus' %}">Брус</a>
        <a class="dropdown-item" href="{% url 'main:brusok' page='brusok' %}">Брусок</a>
        <a class="dropdown-item" href="{% url 'main:vagonka' page='vagonka' %}">Вагонка</a>
        <a class="dropdown-item" href="{% url 'main:imitacia_brusa' page='imitacia_brusa' %}">Имитация бруса</a>
            <a class="dropdown-item" href="{% url 'main:terasnaya_doska' page='terasnaya_doska' %}">Терасная доска </a>
            <a class="dropdown-item" href="{% url 'main:shpuntovanaya_doska' page='shpuntovanaya_doska' %}">Шпунтованная доска </a>
          </div>
        </div>
    <!--<div class="dropdown open">-->
      <!--<button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenu3" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">-->
        <!--Метизы-->
      <!--</button>-->
      <!--<div class="dropdown-menu">-->
        <!--<h6 class="dropdown-header"></h6>-->
        <!--<a class="dropdown-item " href="#">Гвозди</a>-->
        <!--<a class="dropdown-item" href="#">Саморезы</a>-->
        <!--<a class="dropdown-item" href="#"></a>-->
      <!--</div>-->
    <!--</div>-->
    <!--</ul>-->
  <!--</div>-->
  <div class="dropdown open">
      <button class="btn  dropdown-toggle" style="background:#FFDEAD;" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="margin-right: 100px">
        Паркет
      </button>
      <div class="dropdown-menu text-center" style="background:#FFDEAD">
        <h6 class="dropdown-header">Бренды:</h6>
        <a class="dropdown-item" href="{% url 'main:barlinek' page='barlinek' %}">Barlinek</a>
        <a class="dropdown-item" href="{% url 'main:brus' page='brus' %}">Ellett</a>
        <a class="dropdown-item" href="{% url 'main:brusok' page='brusok' %}">Karelia</a>
        <a class="dropdown-item" href="{% url 'main:vagonka' page='vagonka' %}">Polarwood</a>
        <a class="dropdown-item" href="{% url 'main:imitacia_brusa' page='imitacia_brusa' %}">Kahrs</a>
            <a class="dropdown-item" href="{% url 'main:terasnaya_doska' page='terasnaya_doska' %}">Терасная доска </a>
            <a class="dropdown-item" href="{% url 'main:shpuntovanaya_doska' page='shpuntovanaya_doska' %}">Шпунтованная доска </a>
      </div>
  </div>
    <div class="dropdown open">
      <button class="btn  dropdown-toggle" style="background:#CDCDB4;" type="button" id="dropdownMenu6" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="margin-right: 100px">
        Плинтуса
      </button>
      <div class="dropdown-menu text-center" style="background:#CDCDB4">
        <a class="dropdown-item" href="{% url 'main:doska' page='doska' %}">Доска</a>
        <a class="dropdown-item" href="{% url 'main:brus' page='brus' %}">Брус</a>
        <a class="dropdown-item" href="{% url 'main:brusok' page='brusok' %}">Брусок</a>
        <a class="dropdown-item" href="{% url 'main:vagonka' page='vagonka' %}">Вагонка</a>
        <a class="dropdown-item" href="{% url 'main:imitacia_brusa' page='imitacia_brusa' %}">Имитация бруса</a>
            <a class="dropdown-item" href="{% url 'main:terasnaya_doska' page='terasnaya_doska' %}">Терасная доска </a>
            <a class="dropdown-item" href="{% url 'main:shpuntovanaya_doska' page='shpuntovanaya_doska' %}">Шпунтованная доска </a>
      </div>
  </div>
  </ul>
</div>
</nav>

{% block content %}

{% endblock %}

<div  style="margin-top: 450px">
    <footer  style="background:white;" class="footer mt-auto py-3">
      <div class="container" >
            <p class="text-center font-italic" >Woodmart магазин строительных материлов.<a style="color:red"  href="tel:+7981775216"> Позвоните нам по номеру: 8-981-737-52-16</a></p>
      </div>
    </footer>
</div>
</body>
</html>